services:
  - type: web
    name: mailer-api
    runtime: go
    plan: free
    buildCommand: go mod download && go build -o bin/main cmd/sender/main.go
    startCommand: ./bin/main
    envVars:
      - key: POSTMARK_SERVER_TOKEN
        sync: false
      - key: FROM_EMAIL
        value: your-verified-email@yourdomain.com
        sync: false
      - key: FROM_NAME
        value: Your App Name
        sync: false
      - key: PORT
        value: 10000
